### ISSUE TITLE
Not working with yargs

### ISSUE THREAD

**Issue by ogroppo** [sultan99/sexy-require#2]
TypeError: Cannot read property '1' of null
    at callerPath (/node_modules/sexy-require/index.js:41:29)
    at getRoot (/node_modules/sexy-require/index.js:52:22)
    at rootPath (/node_modules/sexy-require/index.js:59:14)
    at Module.require (/node_modules/sexy-require/index.js:84:30)

**Comment by sultan99** [comment]
@ogroppo 
what OS do you use?

**Comment by ogroppo** [comment]
Hi there, using macOS High Sierra

**Comment by sultan99** [comment]
@ogroppo 
can you replace function `callerPath()` by
```js
function callerPath() {
  var err = new Error()
  var re = /at require \(internal\/module\.js:11:18\)\n.+\((.*):\d+:\d+\)/m
  return err.stack.match(re)[1]
}
```
in index.js of sexy-require?

I can't test it right now as I don't have the macOS.
If it is OK I will patch it.

**Comment by sultan99** [comment]
@ogroppo Hi!
Have you check it?

**Comment by ogroppo** [comment]
Sorry mate, I deleted that project now and I am not able to recreate that scenario in a new one. However, I'll be using this package now so I'll let you know if that happens again! cheers
