### ISSUE TITLE
not working with jest?

### ISSUE THREAD

**Issue by andreabisello** [sultan99/sexy-require#5]
this code

```
const puppeteer = require('puppeteer')
const config = require('../lib/config')
```

becomes this one

```
require('sexy-require')
const puppeteer = require('puppeteer')
const config = require('$lib/config')
```

with this file

.paths

![image](https://user-images.githubusercontent.com/2149815/71664831-d3169300-2d5a-11ea-9c18-e96a4458bb90.png)

in the root of the project

but executing test i obtain 

![image](https://user-images.githubusercontent.com/2149815/71664800-b2e6d400-2d5a-11ea-83b0-170c31341d60.png)

**Comment by sultan99** [comment]
Are you using jest?

**Comment by andreabisello** [comment]
@sultan99 yes.

**Comment by sultan99** [comment]
Unfortunately jest use its own native `require` function, `sexy-require` extending nodejs `require`, so it doesn't effect in jest environment.

As a solution you can add `jest.config.js`  file to your application with all directories like you did in `.paths` file, but in regexp. 

Assume your `.path` was:

```sh
$lib = /lib
```

**jest.config.js** would be:

```js
module.exports = {
  moduleNameMapper: {
    '^\\$lib\/(.*)': `<rootDir>/lib/$1`,
  },
}
```

Please check it and let me know if it works for you, so if it does I will add this info in readme.

**Comment by andreabisello** [comment]
yes it works, thanks
