### ISSUE TITLE
Do you have an example of how to get this to work inside a Jest test?

### ISSUE THREAD

**Issue by jdkdev** [sultan99/sexy-require#6]
Hi!

I have sexy-require working fine, but when I tried to implement Jest testing.  It cannot resolve the paths.  I am mimicking the way i do tests like the live server, but I'm sure I am missing something.

Any help is appreciated.

Best,
Jordan

**Comment by sultan99** [comment]
Please check it: https://github.com/sultan99/sexy-require/issues/5#issuecomment-570404127

**Comment by jdkdev** [comment]
Thanks for the speedy response! And the module!
